"""initial schema: users, organizations, memberships, surveys, survey_responses

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-08

The initial revision materializes the full schema straight from the SQLModel
metadata so it can never drift from the models. Subsequent revisions should be
explicit deltas (autogenerated against the metadata).
"""

from alembic import op

import app.models  # noqa: F401 — register tables
from sqlmodel import SQLModel

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    SQLModel.metadata.create_all(bind)


def downgrade() -> None:
    bind = op.get_bind()
    SQLModel.metadata.drop_all(bind)
